[project]
name = "new-asr-service"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask==3.1.2",
    "pytest==8.4.1",
    "torch==2.8.0"
]
